Develop 6 7
LekoLody/AllTasks pull request #1
Opened 2021-12-28 14:42 UTC by LekoLody

Leave a comment

2022-01-04 14:28 UTC, AwesomePotatoJuice requested changes

2022-01-04 14:28 UTC, AwesomePotatoJuice commented on 6_7/src/ArithmeticCalculator.java
> +        if (type == Operation.ADD) {
switch case идеально работает с энамами

2022-01-04 14:28 UTC, AwesomePotatoJuice commented on 6_7/src/ArithmeticCalculator.java
> +            sum = a + b;
test

2022-01-09 11:50 UTC, LekoLody commented on 6_7/src/ArithmeticCalculator.java
> +        if (type == Operation.ADD) {
ok, sha sdelayu

2022-01-09 11:53 UTC, AwesomePotatoJuice approved these changes

2022-01-09 11:53 UTC, merged